<?php
return [
    [
        'nome' => 'Alessandro Pontes da Silva',
        'secretaria' => 'SEFIN',
        'setor' => 'Departamento de Informática',
        'profissao' => 'Técnico em informática',
        'funcao' => 'Técnico em informática',
        'foto' => 'alessandro.jpg',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Alisson Ribeiro Batista',
        'secretaria' => 'SEFIN',
        'setor' => 'Departamento de Informática',
        'profissao' => 'Técnico em informática',
        'funcao' => 'Diretor de informática',
        'foto' => 'alisson.jpg',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Gabriel Giarola',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Administrativo',
        'funcao' => 'Administrativo',
        'foto' => 'gabriel_giarola.png',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Geani Mendonça',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Redatora',
        'funcao' => 'Redatora',
        'foto' => 'geani_mendonca.png',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Heleno Carvalho Paralovo',
        'secretaria' => 'SEDUC',
        'setor' => 'Departamento de Informática',
        'profissao' => 'Chefe em informática',
        'funcao' => 'Técnico em informática',
        'foto' => 'helno.jpg',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo - SEDUC',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Hermes Naves',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Secretário Adjunto',
        'funcao' => 'Secretário Adjunto',
        'foto' => 'hermes_naves.png',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'José Anadelson',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Assessor Setorial',
        'funcao' => 'Assessor Setorial',
        'foto' => 'jose_anadelson.png',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Marco Antônio Vivas',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Técnico em Informática',
        'funcao' => 'Chefe de Informática',
        'foto' => 'vivas.jpg',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Nathália Melo',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Diretora',
        'funcao' => 'Diretora',
        'foto' => 'nathalia_melo.png',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Paulo Henrique Lopes',
        'secretaria' => 'SEMMA',
        'setor' => 'Defesa Civil',
        'profissao' => 'Coordenador - Defesa Civil',
        'funcao' => 'Coordenador - Defesa Civil',
        'foto' => 'paulo_henrique.jpeg',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ],
    [
        'nome' => 'Silvia Cristina Silvado',
        'secretaria' => 'SECOM',
        'setor' => 'Comunicação',
        'profissao' => 'Jornalista',
        'funcao' => 'Jornalista',
        'foto' => 'silvia_cristina.png',
        'contato' => ['email' => 'nome@trescoracoes.mg.gov.br', 'telefone' => '123-456-7890'],
        'status' => '',
        'localizacao' => 'Centro Administrativo',
        'pais' => 'Brasil'
    ]
];